from .independent_set import independent_set
from .isomorphic import isomorphic
from .k_clique import k_clique
from .k_color import k_color
from .minimum_path import minimum_path
from .n_queens import n_queens
from .partition import partition
from .q_sums import q_sums
from .subsequence import subsequence
from .travelling_salesman import travelling_salesman
from .vertex_cover import vertex_cover
